### ISSUE TITLE
RISE not working on JupyterLab

### ISSUE THREAD

**Issue by trevorcampbell** [UBC-DSCI/dsci-100-infra#10]
And images do not work if you try to switch to the Jupyter Notebook interface for some odd reason. Don't see anything about 404s in the logs, and searching for the images in a terminal shows that they're there. This is not high priority so not going to try to fix it.

Instead we should wait for RISE+JupyterLab at https://github.com/damianavila/RISE/pull/605

Should update our images once RISE is compatible

**Comment by firasm** [comment]
Saw this issue linked from the jupyter lab PR. 

I've seen this error before and can confirm it happens **only** when you try to launch clsssic jupyter notebok from the jupyter lab interface. 

Starting the classic jupyter notebook session works just fine 🤷🏽‍♂️. 

Gremlins!

**Comment by trevorcampbell** [comment]
Yeah, our solution this semester has been to just spin up a container with our course image locally and present from there. Which honestly is better than doing it on the server anyway -- less chance for internet / server issues in class!
